spring.application.name=signal
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.djbfmfkzscnyywkvcxkl
spring.datasource.password=i3J1hBfVolLen8nS
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50

# JWT Settings
jwt.secret=v+a5eQe7/K7q3G0j5Z1k9/N8mP4rT2wX6yH1oV3l9+I=
jwt.expiration-ms=3600000


# SPRING_DATA_REDIS_SENTINEL_MASTER=mymaster
# SPRING_DATA_REDIS_SENTINEL_NODES=redis-sentinel-1:26379,...
spring.data.redis.host=localhost
spring.data.redis.port=6379

