server.port=8081

spring.application.name=signal-chat
spring.main.allow-bean-definition-overriding=true

# DB Connection

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.djbfmfkzscnyywkvcxkl
spring.datasource.password=i3J1hBfVolLen8nS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Settings
jwt.secret=v+a5eQe7/K7q3G0j5Z1k9/N8mP4rT2wX6yH1oV3l9+I=
jwt.expiration-ms=3600000

logging.level.org.springframework.web.socket=DEBUG
logging.level.com.evans.signal.chat=DEBUG

# RabbitMQ Connection (AMQP for Consumer)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.org.springframework.messaging.simp.stomp=DEBUG
logging.level.org.springframework.messaging.simp.broker=DEBUG

# Redis - 로컬: standalone (localhost:6379)
# 프로덕션: 환경변수로 Sentinel 주입
spring.data.redis.host=localhost
spring.data.redis.port=6379
