name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        # Gradle 프로젝트가 있는 디렉토리를 지정합니다.
        build-root-directory: backend

    - name: Build with Gradle Wrapper
      working-directory: backend
      run: ./gradlew build

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure() # 항상 실행ㅂ
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
